/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : bigint,
  'title' : string,
  'isChecked' : boolean,
}
export interface CurrencyPair {
  'forex' : boolean,
  'base' : string,
  'quote' : string,
}
export interface DailyLimit {
  'date' : Time,
  'isActive' : boolean,
  'lossLimit' : number,
  'profitTarget' : number,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'direction' : string,
  'rewardAmount' : number,
  'date' : Time,
  'riskAmount' : number,
  'pair' : CurrencyPair,
  'pips' : number,
  'fileAttachment' : [] | [ExternalBlob],
  'notes' : string,
  'entryPrice' : number,
  'exitPrice' : number,
  'lotSize' : number,
}
export interface UserProfile {
  'timezone' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChecklistItem' : ActorMethod<[ChecklistItem], undefined>,
  'addTrade' : ActorMethod<[Trade], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePips' : ActorMethod<[CurrencyPair, number, number, number], number>,
  'calculateWinRateAndRiskReward' : ActorMethod<
    [Array<Trade>],
    { 'averageRiskReward' : number, 'winRate' : number }
  >,
  'findBestAndWorstTrades' : ActorMethod<
    [Array<Trade>],
    { 'bestTrade' : [] | [Trade], 'worstTrade' : [] | [Trade] }
  >,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklist' : ActorMethod<[], Array<ChecklistItem>>,
  'getCurrencyPairs' : ActorMethod<[], Array<CurrencyPair>>,
  'getDailyLimit' : ActorMethod<[], [] | [DailyLimit]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasDailyLimit' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetAllChecks' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDailyLimit' : ActorMethod<[DailyLimit], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];