/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isChecked' : IDL.Bool,
});
export const Time = IDL.Int;
export const CurrencyPair = IDL.Record({
  'forex' : IDL.Bool,
  'base' : IDL.Text,
  'quote' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'direction' : IDL.Text,
  'rewardAmount' : IDL.Float64,
  'date' : Time,
  'riskAmount' : IDL.Float64,
  'pair' : CurrencyPair,
  'pips' : IDL.Float64,
  'fileAttachment' : IDL.Opt(ExternalBlob),
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'lotSize' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'timezone' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const DailyLimit = IDL.Record({
  'date' : Time,
  'isActive' : IDL.Bool,
  'lossLimit' : IDL.Float64,
  'profitTarget' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChecklistItem' : IDL.Func([ChecklistItem], [], []),
  'addTrade' : IDL.Func([Trade], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePips' : IDL.Func(
      [CurrencyPair, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'calculateWinRateAndRiskReward' : IDL.Func(
      [IDL.Vec(Trade)],
      [
        IDL.Record({
          'averageRiskReward' : IDL.Float64,
          'winRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'findBestAndWorstTrades' : IDL.Func(
      [IDL.Vec(Trade)],
      [
        IDL.Record({
          'bestTrade' : IDL.Opt(Trade),
          'worstTrade' : IDL.Opt(Trade),
        }),
      ],
      ['query'],
    ),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklist' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
  'getCurrencyPairs' : IDL.Func([], [IDL.Vec(CurrencyPair)], ['query']),
  'getDailyLimit' : IDL.Func([], [IDL.Opt(DailyLimit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasDailyLimit' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAllChecks' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyLimit' : IDL.Func([DailyLimit], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isChecked' : IDL.Bool,
  });
  const Time = IDL.Int;
  const CurrencyPair = IDL.Record({
    'forex' : IDL.Bool,
    'base' : IDL.Text,
    'quote' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'direction' : IDL.Text,
    'rewardAmount' : IDL.Float64,
    'date' : Time,
    'riskAmount' : IDL.Float64,
    'pair' : CurrencyPair,
    'pips' : IDL.Float64,
    'fileAttachment' : IDL.Opt(ExternalBlob),
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'lotSize' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'timezone' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const DailyLimit = IDL.Record({
    'date' : Time,
    'isActive' : IDL.Bool,
    'lossLimit' : IDL.Float64,
    'profitTarget' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChecklistItem' : IDL.Func([ChecklistItem], [], []),
    'addTrade' : IDL.Func([Trade], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePips' : IDL.Func(
        [CurrencyPair, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'calculateWinRateAndRiskReward' : IDL.Func(
        [IDL.Vec(Trade)],
        [
          IDL.Record({
            'averageRiskReward' : IDL.Float64,
            'winRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'findBestAndWorstTrades' : IDL.Func(
        [IDL.Vec(Trade)],
        [
          IDL.Record({
            'bestTrade' : IDL.Opt(Trade),
            'worstTrade' : IDL.Opt(Trade),
          }),
        ],
        ['query'],
      ),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklist' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
    'getCurrencyPairs' : IDL.Func([], [IDL.Vec(CurrencyPair)], ['query']),
    'getDailyLimit' : IDL.Func([], [IDL.Opt(DailyLimit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasDailyLimit' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAllChecks' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyLimit' : IDL.Func([DailyLimit], [], []),
  });
};

export const init = ({ IDL }) => { return []; };